version: '2'
services:
  build:
    image: jetbrainsinfra/golang:1.11.4
    volumes:
      - .:/work
      - modules:/go/pkg/mod
      - cache:/root/.cache
    working_dir: /work
    command: make build -j 3

  test:
    image: jetbrainsinfra/golang:1.11.4
    volumes:
      - .:/work
      - modules:/go/pkg/mod
      - cache:/root/.cache
    working_dir: /work
#    network_mode: "container:vpn"
    environment:
      VSPHERE_USERNAME:
      VSPHERE_PASSWORD:
    command: make test

volumes:
  modules:
  cache:
